### PR TITLE
Using type_index to avoid RTTIs in program_options. (fixes #10347)

### PR DESCRIPTION
**Pull request by gongminmin**

### CODE REVIEW

**Comment by vprus** [comment]
Thanks for the patch! Sadly, the only thing I can say right now is that I'm not interested in non-RTTI usage and I can't really evaluate whether the change of method types in this patch will break existing clients or not.

**Comment by apolukhin** [comment]
TypeIndex takes care of RTTI on/off and provides additional compile and link time checks (asserting that user do not mix on/off flags for example).

Patch is valid and must break nothing.

**Comment by vprus** [comment]
The patch changes signatures of method. What if existing code uses them? It
will no longer work.

**Comment by apolukhin** [comment]
This signature does not change. `boost::typeindex::type_info` is a typedef for `std::type_info` for cases when `std::type_info` is available (RTTI on or MSVC compiler).

When `std::type_info` and `typeid` are not available, `boost::typeindex::type_info` emulates RTTI.

However the patch is not ideal, `test/options_description_test.cpp` still requires RTTI

**Comment by gongminmin** [comment]
You mean the "dynamic_cast" in test/options_description_test.cpp? Could we make it static_cast and skip the BOOST_CHECK(b)?

**Comment by apolukhin** [comment]
How about adding a new line after the ` [ po-test exception_txt_test.cpp ]` into test/Jamfile.v2:
```
[ run options_description_test.cpp : : : <rtti>off <define>BOOST_NO_RTTI <define>BOOST_NO_TYPEID : options_description_no_rtti_test ]
```

This will build a program_options library without RTTI and run the `options_description_test.cpp` one more time.

Dynamic cast can be put into `#ifndef BOOST_NO_RTTI` block.

**Comment by gongminmin** [comment]
Good idea. I'll submit a patch ASAP.

**Comment by vprus** [comment]
This patch produces compilation error for me:

    options_description_test.cpp:34:50: error: invalid static_cast from type ‘boost::shared_ptr<const   boost::program_options::value_semantic>::element_type* {aka const  boost::program_options::value_semantic*}’ to type ‘const boost::program_options::typed_value_base*’
         (desc.find("foo", false).semantic().get());

**Comment by gongminmin** [comment]
I think we have to keep that part of code inside #ifndef BOOST_NO_RTTI/#endif, unless there is a way to avoid the dynamic_cast for multiple inheritance. In my new commit the compiling errors are fixed. Sorry for the inconvenient.

**Comment by vprus** [comment]
That seem to suggest the library is not quite usable without RTTI? In that, you can check whether typed_value_base holds a particular type, but there's no way to get at typed_value_base from value_semantics, so the only way to call typed_value_base::value_type is if you already have a class derived from typed_value_base, in which case you probably know it's type anyway?

**Comment by gongminmin** [comment]
Yes, it looks like if a user need to call typed_value_base::value_type(), there is no way to avoid RTTI. I tried to add a typed_value_base* parameter to options_description's constructor but that means it's not compatible to all existing user code.

For my project, we don't call value_type() so we can live with other parts of program_options without RTTI. I think I have to pull out this request since it can't fully support all features.

**Comment by vprus** [comment]
Maybe it would be possible to not defined value_type() at all if RTTI is off? Though that would make typed_value_base not useful at all - maybe that class can be only defined if RTTI is enabled?

**Comment by gongminmin** [comment]
I refined my commit to disable typed_value_base when RTTI is off.

**Comment by vprus** [comment]
Thanks, I've pushed this change. Please take a look at the follow-up change I've committed - bd1d0bd - is it all right?

**Comment by gongminmin** [comment]
Yes, it's correct. And if we are using std::type_info, we can even revert the #include <boost/type_index.hpp> to #include <typeinfo> in include/boost/program_options/value_semantic.hpp, and boost::typeindex::type_id<T> to typeid(T) test/options_description_test.cpp.

**Comment by vprus** [comment]
Thanks, done in 0756d35. Out of curiousity, what's your particular reason to build with RTTI off?

**Comment by gongminmin** [comment]
When compiling my project with clang for Windows (weird right?), RTTI causes some trouble in release mode. Since we don't actually use RTTI in release, we just turn it off. Then there are some compiling errors in value_semantic.hpp, so I'm looking for ways to make a compatible code for both RTTI-on and RTTI-off for program_options.

**Comment by gongminmin** [comment]
Thanks for your modification. There is one more place needs to be reverted. In include/boost/program_options/value_semantic.hpp, line 366. It can be "const std::type_info& value_type() const".

**Comment by vprus** [comment]
Indeed, done now.

**Comment by gongminmin** [comment]
Thanks!

**Pull request closed without merging**
