### PR TITLE
Support boost::optional option variables.

### PR DESCRIPTION
**Pull request by ecatmur**
For https://svn.boost.org/trac/boost/ticket/7495

### CODE REVIEW

**Comment by vprus** [comment]
Edward,

sorry for missing your excellent patch; it's now applied.

**Comment by trylle** [comment]
[The changelog](http://www.boost.org/users/history/version_1_64_0.html) indicates that this pull request is included in 1.64.0, but the download does not appear to contain these modifications. I assume the changelog is wrong?

**Comment by vprus** [comment]
You are correct, the changelog is wrong, and the change was not included in 1.64.0 due to my oversight, I apologize. The develop branch is now merged to master for 1.65.0, so the change will appear there. I have also updated changelog to match reality.

**Comment by trylle** [comment]
Thanks!

**Pull request closed without merging**
