### PR TITLE
Specified default value for the template argument of parse_config_file

### PR DESCRIPTION
**Pull request by emreturkay**

### CODE REVIEW

**Comment by vprus** [comment]
Thanks for the PR! For my education, what problem does this solve?

**Comment by emreturkay** [comment]
The change defines a default value for the "class charT" template argument of parse_config_file function for compilers supporting C++ 11 "default template arguments for function templates" feature (BOOST_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS).

This change allows one to write

	parse_config_file("example.cfg", desc)

instead of

	parse_config_file<char>("example.cfg", desc)

As a bonus, the code example in the "Storage Component" of the boost program options documentation (http://www.boost.org/doc/libs/1_66_0/doc/html/program_options/overview.html) will be valid with this change.

	variables_map vm;
	store(parse_command_line(argc, argv, desc), vm);
	store(parse_config_file("example.cfg", desc), vm);
	notify(vm);

**Comment by emreturkay** [comment]
The change defines a default value for the "class charT" template argument of parse_config_file function for compilers supporting C++ 11 "default template arguments for function templates" feature (BOOST_NO_CXX11_FUNCTION_TEMPLATE_DEFAULT_ARGS).

This change allows one to write

	parse_config_file("example.cfg", desc)

instead of

	parse_config_file<char>("example.cfg", desc)

As a bonus, the code example in the "Storage Component" of the boost program options documentation (http://www.boost.org/doc/libs/1_66_0/doc/html/program_options/overview.html) will be valid with this change.

	variables_map vm;
	store(parse_command_line(argc, argv, desc), vm);
	store(parse_config_file("example.cfg", desc), vm);
	notify(vm);

**Comment by vprus** [comment]
Thanks, this is now merged to develop.

**Pull request merged**
